package Vistas;

import Entidades.Alumno;
import Entidades.Inscripcion;
import java.util.ArrayList;

public class Menu extends javax.swing.JFrame {
    
    private ArrayList<Alumno> listaAlumnos;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiFAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiFMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiAlumPorMateria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiNotas = new javax.swing.JMenuItem();
        jmiInscripciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        jmiFAlumno.setText("Formulario Alumno");
        jmiFAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jmiFMateria.setText("Formulario Materia");
        jmiFMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        jmiAlumPorMateria.setText("Materia por Alumno");
        jmiAlumPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumPorMateriaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAlumPorMateria);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Administración");

        jmiNotas.setText("Notas");
        jmiNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNotasActionPerformed(evt);
            }
        });
        jMenu4.add(jmiNotas);

        jmiInscripciones.setText("Inscripciones");
        jmiInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(jmiInscripciones);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumno fAlum = new FormularioAlumno();
        fAlum.setVisible(true);
        escritorio.add(fAlum);
    }//GEN-LAST:event_jmiFAlumnoActionPerformed

    private void jmiFMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMateria1 fMat = new FormularioMateria1();
        fMat.setVisible(true);
        escritorio.add(fMat);
    }//GEN-LAST:event_jmiFMateriaActionPerformed

    private void jmiNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNotasActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        FormularioNotas fNotas = new FormularioNotas();
        fNotas.setVisible(true);
        escritorio.add(fNotas);
    }//GEN-LAST:event_jmiNotasActionPerformed

    private void jmiAlumPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumPorMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        MateriasPorAlumnos fAlumMat = new MateriasPorAlumnos();
        fAlumMat.setVisible(true);
        escritorio.add(fAlumMat);
    }//GEN-LAST:event_jmiAlumPorMateriaActionPerformed

    private void jmiInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInscripcionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripcion fInsc = new FormularioInscripcion();
        fInsc.setVisible(true);
        escritorio.add(fInsc);
    }//GEN-LAST:event_jmiInscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAlumPorMateria;
    private javax.swing.JMenuItem jmiFAlumno;
    private javax.swing.JMenuItem jmiFMateria;
    private javax.swing.JMenuItem jmiInscripciones;
    private javax.swing.JMenuItem jmiNotas;
    // End of variables declaration//GEN-END:variables
}
